# Generated by Django 5.0.2 on 2024-04-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_genre_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
