# Generated by Django 5.0.2 on 2024-04-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_movies_genre_delete_genre_delete_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.FileField(upload_to='movie_logos/'),
        ),
    ]
