# Generated by Django 5.0.2 on 2024-04-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_movie_movie_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
